/**
 * Global constants definition file
 * !THIS IS NOT TIED WITH THE REDUX LAYER
 */
const constants = {
  SELECTED_SALON: 'SELECTED_SALON',
  PORTAL_SIGNOUT: 'PORTAL_SIGNOUT',
  INACTIVE_USER_TIME_THRESHOLD: 1800000, // 30 min
  USER_ACTIVITY_THROTTLER_TIME: 5000, // 5 sec
  GRACE_PERIOD_SESSION_TIMEOUT: 180000, // 3 min
  SELECTED_SERVICES_CATEGORIES: 'SERVICES_CATEGORIES',
  SELECTED_SERVICES_STATUS: 'SERVICE_STATUS',
  SELECTED_DISCOUNTS_VALIDITY: 'DISCOUNT_VALIDITY',
  SELECTED_DISCOUNTS_STATUS: 'DISCOUNT_STATUS',
  SELECTED_EMPLOYEE_STATUS: 'EMPLOYEE_STATUS',
  SELECTED_EMPLOYEE_SALON_WORKER: 'EMPLOYEE_SALON_WORKER',
  SELECTED_SCHEDULE_VIEW: 'SCHEDULE_VIEW',
  SELECTED_SCHEDULE_DAY: 'SCHEDULE_DAY',
  SELECTED_PRODUCTS_TYPE: 'PRODUCTS_TYPE',
  SELECTED_PRODUCTS_CATEGORIES: 'PRODUCTS_CATEGORIES',
  SELECTED_PRODUCTS_BRANDS: 'PRODUCTS_BRANDS',
  SELECTED_PRODUCTS_STATUS: 'PRODUCTS_STATUS',
  SEARCH_CRITERIA_DISCOUNTS: 'DISCOUNTS_SEARCH_TEXT',
  SEARCH_CRITERIA_PRODUCTS: 'PRODUCTS_SEARCH_TEXT',
  SEARCH_CRITERIA_SERVICES: 'SERVICES_SEARCH_TEXT',
  SELECTED_ALL_EMPLOYEES_SCHEDULE_TOGGLE: 'SCHEDULES_ALL_EMPLOYEES',
  SELECTED_COUNTRY_CODE: 'SELECTED_COUNTRY_CODE',
  SELECTED_CURRENCY_CODE: 'SELECTED_CURRENCY_CODE',
  SELECTED_LANGUAGE_CODE: 'SELECTED_LANGUAGE_CODE',
  SELECTED_EMPLOYEES_FOR_SCHEDULE: 'SELECTED_EMPLOYEES_FOR_SCHEDULE',
  SELECTED_DAYS_FOR_SCHEDULE: 'SELECTED_DAYS_FOR_SCHEDULE',
  SELECTED_ACTIVITY_FOR_SCHEDULE: 'SELECTED_ACTIVITY_FOR_SCHEDULE',
  SELECTED_NOTES_FOR_SCHEDULE: 'SELECTED_NOTES_FOR_SCHEDULE'
  // For Testing
  // INACTIVE_USER_TIME_THRESHOLD: 60000, // 1 min
  // USER_ACTIVITY_THROTTLER_TIME: 5000, // 5 sec
  // GRACE_PERIOD_SESSION_TIMEOUT: 20000 // 20 sec
}

export default constants
